### ISSUE TITLE
App Crashes upon completion of test?

### ISSUE THREAD

**Issue by james474789** [christianrehn/CombineTest#5]
I created a random 35-100yd carry test and everytime the last shot completes (I tested 10,5,5,5 shot tests) the app becomes unresponsive and must be restarted.

This didnt happen in previous versions

**Comment by christianrehn** [comment]
Thank you for your feedback. I will check and fix this within the next days.

**Comment by christianrehn** [comment]
@james474789 Could you please check the version number you are using, is it 3.2.3?
I cannot reproduce the problem. Does you drill configuration look like mine?
![image](https://github.com/christianrehn/CombineTest/assets/72261047/410e8211-872c-42ab-869c-06559ced9faa)

**Comment by christianrehn** [comment]
@james474789 What "Shots Update Type" are you using?
![image](https://github.com/christianrehn/CombineTest/assets/72261047/56d2b17e-a39b-4a50-ae4d-89b9bbfd1c5c)

![image](https://github.com/christianrehn/CombineTest/assets/72261047/1afef3a1-58ac-4b6d-9ec7-789eb867df1c)

**Comment by james474789** [comment]
Yes,
3.2.3. Setup was the same as yours. Shots update is event like yours.
Interestingly I notice that I get the same issue if I attempt to load a
saved session:
https://www.youtube.com/watch?v=st6z9UH-yb0

**Comment by christianrehn** [comment]
Thank you, I think I found the problem. I will build a new release 3.2.4 with a bug fix today.

**Comment by james474789** [comment]
Just tested 3.2.4 and it looks good - working as expected

**Comment by christianrehn** [comment]
@james474789 Could you please test the new version 3.2.4. 
Your already saved sessions without a distanceGenerator type will be ignored and not shown anymore. New sessions will be saved together with their distanceGenerator type.
If you want to see your old sessions you have to edit you session.json file manually.
You can find it under C:\Users\<user name>\AppData\Roaming\CombineTest\Sessions.json
"distanceGenerator": {
        "type": "RandomDistancesGenerator",
